version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm ci
      - run: npm test -- --reporter min
      - run: npm run coverage-ci
  build:
    machine: true
    steps:
      - checkout
      - run: docker build --build-arg SONGKICK_API_KEY=${SONGKICK_API_KEY} -t ${DOCKER_REGISTRY}/${DOCKER_USER}/gigmap/gigmap-api:latest .
      - run: docker login -u ${DOCKER_USER} --password ${DOCKER_PASSWORD} ${DOCKER_REGISTRY}
      - run: docker push ${DOCKER_REGISTRY}/${DOCKER_USER}/gigmap/gigmap-api:latest
  deploy:
      machine: true
      steps:
        - run: ssh ${DEPLOY_USER}@${DEPLOY_HOST} "docker pull ${DOCKER_REGISTRY}/${DOCKER_USER}/gigmap/gigmap-api:latest && docker service update --force gigmap-api"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - build:
          context: GigMap
          requires:
            - test
      - deploy:
          context: GigMap
          requires:
            - build
          filters:
            branches:
              only: master